# Dockerfile
# Use the official Node.js image as a base image
FROM node:18-alpine

# Create and change to the app directory
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY source/frontend/package*.json ./

COPY source/frontend/.env ./.env

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY source/frontend .

# Build the app
RUN npm run build

# Expose the port
EXPOSE 5173

# Start the app
CMD ["npm", "run", "dev"]
